////////////////////// APP TYPES
export const SAVE_ALL_CATEGORIES = "SAVE_ALL_CATEGORIES";
export const SAVE_FETCHED_SERVICES = "SAVE_FETCHED_SERVICES";
export const SAVE_FETCHED_SERVICE_DETAIL = "SAVE_FETCHED_SERVICE_DETAIL";
export const SAVE_FETCHED_APP_REVIEWS = "SAVE_FETCHED_APP_REVIEWS";

/////////////////////////CART TYPE
export const SAVE_USER_CART = "SAVE_USER_CART";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

///////////////////////// ORDER TYPE
export const SAVE_ORDERS = "SAVE_ORDERS";
export const SAVE_NEW_ORDER = "SAVE_NEW_ORDER";

/////////////////////////// USER PROFILE
export const SAVE_PROFILE = "SAVE_PROFILE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

/////////////////////// AUTH TYPES
export const SAVE_USER_AUTH_HASH = "SAVE_USER_AUTH_HASH";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT = "LOGOUT";

/////////////////////// ADMIN TYPES
export const FETCH_ACTIVE_ORDERS = "FETCH_ACTIVE_ORDERS";
export const FETCH_ALL_SERVICES = "FETCH_ALL_SERVICES";
export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const FETCH_ALL_ORDERS = "FETCH_ALL_ORDERS";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SAVE_NEW_SERVICE = "SAVE_NEW_SERVICE";
export const NEW_ORDER_STATUS = "NEW_ORDER_STATUS";
export const FETCH_ORDER_DETAIL = "FETCH_ORDER_DETAIL";
export const SAVE_NEW_ADMIN_REVIEW = "SAVE_NEW_ADMIN_REVIEW";
export const SAVE_ADMIN_REVIEW = "SAVE_ADMIN_REVIEW";
export const SAVE_ADMIN_EDITED_REVIEW = "SAVE_ADMIN_EDITED_REVIEW";
export const SAVE_DELETED_REVIEW = "SAVE_DELETED_REVIEW";
